### ISSUE TITLE
False issue tracker link in docs 

### ISSUE THREAD

**Issue by cfgmr** [Materials-Data-Science-and-Informatics/fair-python-cookiecutter#26]
**Describe the bug**
The link to the issue tracker in the [docs](https://materials-data-science-and-informatics.github.io/fair-python-cookiecutter/latest/contributing/) is wrong and results in a 404. The link is 

`https://materials-data-science-and-informatics.github.io/fair-python-cookiecutter/latest/contributing/{{ cookiecutter.project_repo_url }}/issues` [sic]

**To Reproduce**
1. https://materials-data-science-and-informatics.github.io/fair-python-cookiecutter/latest/contributing/
2. Click on 'If you have questions or difficulties using this software, please use the [issue tracker](https://materials-data-science-and-informatics.github.io/fair-python-cookiecutter/latest/contributing/%7B%7B%20cookiecutter.project_repo_url%20%7D%7D/issues).'
3. See error

**Comment by mustafasoylu** [comment]
Thank you for the feedback, I will fix it in the next version.
